### ISSUE TITLE
Remove FastML sources and binaries from repository

### ISSUE THREAD

**Issue by boulund** [b16joski/bactpipe_nextflow#13]
I just noticed that there are some large commits that I think might have been accidental. Amongst other things, the commit in question includes the source code for another program (FastML), as well as a compiled version. This is a severe problem. We can't have the source code and binaries (or source code tarballs) of other software commited into the repo. Firstly, because it in almost all cases violates the copyright and distribution licenses of these tools, secondly because it clutters and unnecessarily bloats the repository, and thirdly because it would give us a lot more work keeping these third-party tools up-to-date in our repository (if we're even allowed to include them in the first place). 

Instead, I think we should put links to the websites of all important dependencies in the README so that pipeline users easily can find and download the prerequisite software. That way, we don't have to take responsibility to keep the latest version of these tools inside our own repository either. Just make sure to include the version of each tool that has been tested with the pipeline.

@b16joski, this is an excellent opportunity for you to learn how to remove accidentally commited files from a git repository. It is not enough to just remove them in a new commit, since they will still remain in the repository commit history. They need to be entirely removed from history as well. I've only done this kind of operation once, and that was in Mercurial, not Git. 

As far as I know, there are only two reasonable options: `git filter-branch` or https://rtyley.github.io/bfg-repo-cleaner/ . Research what is the best option in this case and remove all the third-party files from the repository history. 

Make sure you document your steps to solving this issue in this discussion thread so we can all refer to it in the future. Let us know if you encounter issues and need help. This is a tricky operation that could possibly screw up the repository (changing history is very precarious).

**Comment by boulund** [comment]
This is the commit that included FastML: https://github.com/b16joski/bactpipe_nextflow/commit/b5376a8162a13b0637e0c7051c7606492ab698fb

**Comment by thorellk** [comment]
I agree, it is important that we keep things clean and only include the steps and parts that are essential so that we don't clutter up the repository and violate any licences. As far as I can see none of the things in that commit needs to be there and seems like you have committed your whole bin from uppmax including old BACTpipe scripts etc.

Also, I think it is important that we properly comment each commit not only with "my second commit" but with the changes this commit addresses eg "added strain specific Prokka output directories" etc so that it is easy to follow which changes that have been implemented for each new commit. Rather comment too much than too little :)

**Comment by boulund** [comment]
If no files in the commit are supposed to be in the repository, another option might be `git rebase -i` as well, but please do some research to figure out the best way to delete a commit or files from history. I'm not an expert on these things.

**Comment by boulund** [comment]
We decided to completely nuke the entire repo history (`$rm -rfv .git`) and then re-initalize a new git repo in the same folder, using only the files we wanted to keep. This created a new "first commit".
