### ISSUE TITLE
Rewrite FilterAssembly.pl to python

### ISSUE THREAD

**Issue by thorellk** [b16joski/bactpipe_nextflow#6]
...and make sure it is python 3-compatible

**Comment by thorellk** [comment]
Check and implement https://github.com/tseemann/shovill instead of SPAdes + FilterAssembly instead.

**Comment by b16joski** [comment]
We discussed due to the many dependencies required by shovill, we shall use it in  Bactpipe 2.0.

**Comment by thorellk** [comment]
I agree @b16joski, it is better that we implement it in 2.0
