### ISSUE TITLE
Rewrite assembly_stats.py

### ISSUE THREAD

**Issue by boulund** [b16joski/bactpipe_nextflow#8]
Rewrite in Python 3.5+ and preferably remove unnecessary Biopython dependency.

**Comment by boulund** [comment]
BBTools have a program called `stats.sh` that computes basic assembly statistics such as scaffold count, N50, L50, GC content, gap percent, etc.
Why not use it, since bactpipe is already dependent on a BBMap installation, it is no extra effort to depend on `stats.sh` for our assembly statistics. 
What do you think @thorellk @b16joski ?

**Comment by thorellk** [comment]
That sounds really neat. Also good to not have an unnecessary amount of own scripts to maintain :)

**Comment by boulund** [comment]
We could actually rely on a more of the BBTools programs, I think. Since we're already depending on BBTools being installed, I see little reason to write our own scripts for doing what we can solve with BBTools. There is one for renaming reads (`rename.sh`), that can rename the contigs, possibly like we're currently doing with `rename_fasta.py`. We could create another issue regarding that.

**Comment by b16joski** [comment]
This is really good I should try (stats.sh ) on the current dataset.

**Comment by thorellk** [comment]
Nice, hope it works well

**Comment by boulund** [comment]
We just discussed that it seems that `stats.sh` from BBTools appears to give sufficient information. 
The next step would be to implement `stats.sh` in the pipeline and have it replace the original `assembly_stats.py`.

**Comment by boulund** [comment]
Check out `statswrapper.sh` for a way to put statistics for many different contig files into one single statistics file.

**Comment by thorellk** [comment]
Decided to implement BBTools stats.sh and get rid of AssemblyStats.py

**Comment by boulund** [comment]
I'll ask Brian about `statswrapper.sh` and "one line per file" output.

**Comment by boulund** [comment]
Ok, Brian replied already. The fix is embarassingly simple: add the flag `format=3`... 

Here's the output of: `statswrapper.sh 162-C_covfiltered.fasta G83-2_covfiltered.fasta format=3`
```
n_scaffolds     n_contigs       scaf_bp contig_bp       gap_pct scaf_N50        scaf_L50        ctg_N50 ctg_L50 scaf_N90        scaf_L90        ctg_N90 ctg_L90 scaf_max ctg_max scaf_n_gt50K    scaf_pct_gt50K  gc_avg  gc_std  filename
30      30      1629978 1629978 0.000   5       111265  5       111265  15      42884   15      42884   227893  227893  12      83.315  0.38798 0.02879 /home/boulund/research/H.pylori/WP_helicobacter/G162-C_covfiltered.fasta
31      31      1630710 1630710 0.000   5       111288  5       111288  15      42884   15      42884   228577  228577  12      83.008  0.38801 0.02832 /home/boulund/research/H.pylori/WP_helicobacter/G83-2_covfiltered.fasta
```

**Comment by thorellk** [comment]
Decided to implement statswrapper.sh in Bactpipe 2.0
