### ISSUE TITLE
Change so that each sample gets an own prokka output folder

### ISSUE THREAD

**Issue by thorellk** [b16joski/bactpipe_nextflow#9]
So that instead of that the pipeline outputs all prokka output files into the same folder, there will be separate folders, i.e. prokka/${sample_id}

**Comment by b16joski** [comment]
fixed

**Comment by boulund** [comment]
@b16joski, when you finish working on an issue and you feel satisified with your work you can close the issue, either via the web interface on Github, or when you commit the work that fixes the issue, include the phrase `fixes #9` (of course with the correct issue number depending on what issue you are working on) in the commit message to have Github automatically close the issue when you push the commit.
